### ISSUE TITLE
bash: yarn-minify: command not found

### ISSUE THREAD

**Issue by Sogl** [djmitche/yarn-minify#1]
Just added this package to my project with `yarn add yarn-minify --dev` and try to minify from command-line:
```bash
laradock@480a372e6bd8:/var/www/sogl$ yarn-minify
bash: yarn-minify: command not found
```

**Comment by djmitche** [comment]
Hi @Sogl!  For reasons I don't entirely understand, binaries for node things are stored in `node_modules/.bin`, so you would need to either add `node_modules/.bin` to $PATH, or just run `node_modules/.bin/yarn-minify`.

**Comment by Sogl** [comment]
```

laradock@480a372e6bd8:/var/www/sogl$ node_modules/.bin/yarn-minify
/var/www/sogl/node_modules/@yarnpkg/lockfile/index.js:5064
    throw new SyntaxError(`${msg} ${this.token.line}:${this.token.col} in ${this.fileLoc}`);
    ^

SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/var/www/sogl/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/var/www/sogl/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/var/www/sogl/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at Object.module.exports.exports.default (/var/www/sogl/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at minify (/var/www/sogl/node_modules/yarn-minify/index.js:10:35)
    at Object.<anonymous> (/var/www/sogl/node_modules/yarn-minify/main.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
```

I found the similar error here: https://github.com/renovatebot/renovate/issues/5230#issuecomment-612887676
https://github.com/yarnpkg/yarn/issues/7100

**Comment by djmitche** [comment]
Hm, it's possible that your yarn.lock file is in a new format -- I actually don't use this library anymore, so I might have missed it.  If upgrading `lockfile` helps, I'd be happy to merge a PR to do so.

**Comment by duyleekun** [comment]
I think you can just `npx yarn-minify`. I just tried and it works wonderfully

**Comment by djmitche** [comment]
Oh, cool @duyleekun -- do you want to make a PR to update the instructions?
